import { Header } from "@/components/Header";
import "./globals.css";
import type { Metadata } from "next";
import { Saira } from "next/font/google";
import { FilterContextProvider } from "@/contexts/filter-context";

const saira = Saira({
  subsets: ["latin"],
  weight: ["400", "300", "500"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={saira.className}>
        <FilterContextProvider>
          <Header />
          {children}
        </FilterContextProvider>
      </body>
    </html>
  );
}
